version: '3'
services:

    redis:
      image: redis:alpine #EXPOSE 6379
      container_name: "redis"
      

    user-service:
      image: webdevtoolsandtech/user-service
     
      environment:
        REDIS_ADDRESS: redis:6379
    
    currency-calculator:
      image: currency-calculator

    currency-frontend:
      image: webdevtoolsandtech/currency-frontend
      
    currency-backend:
      image: webdevtoolsandtech/currency-backend
      ports: 
        - "8000:80"
      environment:
        REDIS_ADDRESS: redis:6379
        SESSION_SECRET: 'lalala'
        USER_SERVICE_ADDRESS: user-service:80
        FRONTEND_ADDRESS: currency-frontend:80
        CALCULATOR_ADDRESS: currency-calculator:3000
      